'use client';
import {ZoomImage} from '../../../components/zoom-image';
import {CaseContents} from '../../../components/case-contents';
import Link from '../../../components/site-link';
import {ContactCTA,Reveal,Visual} from '../../../components/site';
import type {Project} from '../../../lib/projects';
import {choose,localizeProject,useLanguage} from '../../../lib/i18n';
import {VelosopSocialMerch} from '../../../components/velosop-social-merch';
import {LisyaNoraStory} from '../../../components/lisya-nora-story';
import {LightingStory} from '../../../components/lighting-story';
import {EventInvitationStory} from '../../../components/event-invitation-story';
import {CaseProfileCard} from '../../../components/case-profile';
import {AppliedCaseStory} from '../../../components/applied-case-story';
import {PrintProjectIndex} from '../../../components/print-project-index';
import {caseProfiles} from '../../../lib/case-profiles';
import {PrintCollectionStory,VelosopApplications} from '../../../components/print-media';

export function CaseContent({project,next}:{project:Project;next:Project}){
  const {language}=useLanguage();const p=localizeProject(project,language);const profile=caseProfiles[p.slug];
  return <main className={profile?'applied-case-page':p.printItems?'print-collection-page':''}>
    <section className="case-hero wrap"><Link className="eyebrow back-link" href="/work">← {choose(language,'ВСЕ РАБОТЫ','ALL WORK')}</Link><div className="case-title-row"><span>{p.number} / {choose(language,'КЕЙС','CASE STUDY')}</span><div className="title-mask"><h1>{p.title}<span className="period">.</span></h1></div></div>
      {profile?<div className="applied-case-meta"><span>{p.disciplines.join(' / ')}</span>{p.year!=='—'&&<span>{p.year}</span>}</div>:<><div className="case-meta"><div><span>{choose(language,'ГОД','YEAR')}</span><strong>{p.year}</strong></div><div><span>{choose(language,'НАПРАВЛЕНИЯ','DISCIPLINES')}</span><strong>{p.disciplines.join(' / ')}</strong></div><div><span>{choose(language,'РОЛЬ','ROLE')}</span><strong>{p.slug==='velosop'?choose(language,'ОРГАНИЗАТОР / ГРАФИЧЕСКИЙ ДИЗАЙНЕР / АРТ-ДИРЕКШН','ORGANIZER / GRAPHIC DESIGNER / ART DIRECTION'):choose(language,p.slug==='print-production'?'ДИЗАЙН / РАБОТА С ПЕЧАТНЫМИ МАТЕРИАЛАМИ':'ГРАФИЧЕСКИЙ ДИЗАЙН / АРТ-ДИРЕКШН',p.slug==='print-production'?'DESIGN / WORK WITH PRINTED MATERIALS':'GRAPHIC DESIGN / ART DIRECTION')}</strong></div></div><p className="case-intro">{p.description}</p></>}
      <CaseContents/>
    </section>
    {profile?<CaseProfileCard profile={profile}/>:<div className="case-visual wrap image-on-load"><Visual project={project} variant="case-cover"/></div>}
    {p.slug==='velosop'?<VelosopStory project={project}/>:p.slug==='lisya-nora'?<LisyaNoraStory/>:p.slug==='lighting'?<LightingStory/>:p.slug==='print-production'?<PrintProjectIndex/>:p.slug==='event-invitation'?<EventInvitationStory/>:profile?<AppliedCaseStory profile={profile}/>:p.printItems?<PrintCollectionStory items={p.printItems}/>:<GeneralStory project={project}/>}
    <section className="next-project wrap"><span className="eyebrow">{choose(language,'СЛЕДУЮЩИЙ ПРОЕКТ','NEXT PROJECT')} / {next.number}</span><Link href={'/work/'+next.slug}>{localizeProject(next,language).title}<span>↗</span></Link></section><ContactCTA/>
  </main>
}

function VelosopStory({project}:{project:Project}){const {language}=useLanguage();return <div className="case-story wrap"><Reveal className="story-text"><span className="eyebrow">01 / {choose(language,'О ПРОЕКТЕ','ABOUT')}</span><p>{choose(language,'ВелоСОП — ежегодный велосипедный проект, визуальную систему которого я развиваю более 7 лет. Она охватывает айдентику, социальные сети, мерч, полиграфию и оформление мероприятия.','VeloSOP is an annual cycling project whose visual system I’ve developed for more than seven years. It spans identity, social media, merchandise, print and event design.')}</p></Reveal><Reveal className="case-stat"><span>2026 / {choose(language,'КАРЕЛИЯ, ЛАДОЖСКИЕ ШХЕРЫ','KARELIA, LADOGA SKERRIES')}</span><strong>60</strong><span>{choose(language,'УЧАСТНИКОВ','PARTICIPANTS')}</span></Reveal><Reveal className="story-section"><span className="eyebrow">02 / {choose(language,'ВИЗУАЛЬНАЯ СИСТЕМА + ПИКСЕЛЬНАЯ ГРАФИКА','VISUAL SYSTEM + PIXEL ART')}</span><h2>{language==='ru'?<>ОДНА СИСТЕМА.<br/>МНОГО ФОРМАТОВ.</>:<>ONE SYSTEM.<br/>MANY FORMATS.</>}</h2><VelosopBanners/><p>{choose(language,'Пиксельная графика принадлежит проекту: она живёт в его коммуникации и носителях, сохраняя единый характер в разных размерах.','Pixel graphics belong to the project itself. They carry a consistent character across communication and physical formats of different sizes.')}</p></Reveal><Reveal className="story-section"><span className="eyebrow">03 / DIGITAL + {choose(language,'ПЕЧАТЬ + МЕРЧ','PRINT + MERCH')}</span><h2>{language==='ru'?<>НА ЭКРАНЕ.<br/>В РЕАЛЬНОСТИ.</>:<>ON SCREEN.<br/>IN THE WORLD.</>}</h2><VelosopApplications/></Reveal><VelosopSocialMerch/><Reveal className="story-text result"><span className="eyebrow">09 / {choose(language,'ИИ, ПРОЦЕСС + РЕЗУЛЬТАТ','AI, PROCESS + REAL LIFE')}</span><p>{choose(language,'От цифрового макета до реального маршрута: визуальные решения проверяются в коммуникации, печати и на самом мероприятии.','From digital artwork to a real route, the visual ideas are tested in communication, print and the event itself.')}</p><div className="result-metrics"><span>{choose(language,'БОЛЕЕ 7 ЛЕТ / ПРОЕКТ','OVER 7 YEARS / PROJECT')}</span><span>{choose(language,'60 УЧАСТНИКОВ / 2026','60 PARTICIPANTS / 2026')}</span><span>{choose(language,'600K+ ₽ / ГРАНТЫ','600K+ ₽ / GRANTS')}</span></div></Reveal></div>}
function GeneralStory({project}:{project:Project}){const {language}=useLanguage();const p=localizeProject(project,language);return <div className="case-story wrap"><Reveal className="story-text"><span className="eyebrow">01 / {choose(language,'КОНТЕКСТ','CONTEXT')}</span><p>{p.description}</p></Reveal><Reveal className="story-section"><span className="eyebrow">02 / {choose(language,'ВИЗУАЛЬНАЯ ИСТОРИЯ','VISUAL STORY')}</span><h2>{p.title}</h2><div className="story-pair"><Visual project={project} variant="story-tile" label={choose(language,'СИСТЕМА / 01','SYSTEM / 01')}/><Visual project={project} variant="story-tile muted" label={choose(language,'ДЕТАЛЬ / 02','DETAIL / 02')}/></div></Reveal><Reveal className="story-section"><span className="eyebrow">03 / {choose(language,'ПРИМЕНЕНИЕ','APPLICATION')}</span><Visual project={project} variant="story-wide" label={choose(language,'ПРИМЕНЕНИЕ / 03','APPLICATION / 03')}/></Reveal><Reveal className="story-text result"><span className="eyebrow">04 / {choose(language,'РЕЗУЛЬТАТ','RESULT')}</span><p>{choose(language,'Изображения и подробности этого кейса появятся после добавления исходных материалов проекта.','Images and further details will be added when the original project materials are available.')}</p></Reveal></div>}

function VelosopBanners(){const {language}=useLanguage();return <div className="case-banner-gallery">
  <figure><ZoomImage src="/images/velosop-billboard.webp" srcSet="/images/velosop-billboard-small.webp 960w, /images/velosop-billboard.webp 1824w" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 1728px) 46vw, 788px" width={1824} height={1368} alt={choose(language,'Мокап зелёного наружного баннера ВелоСОП с пиксельной графикой','Green VeloSOP outdoor banner mockup with pixel graphics')} loading="lazy" decoding="async"/><figcaption><span>01 / {choose(language,'БАННЕР','BANNER')}</span><span>{choose(language,'ПИКСЕЛЬНАЯ ГРАФИКА','PIXEL GRAPHICS')}</span></figcaption></figure>
  <figure><ZoomImage src="/images/velosop-banner-2026.webp" srcSet="/images/velosop-banner-2026-small.webp 768w, /images/velosop-banner-2026.webp 1536w" sizes="(max-width: 650px) calc(100vw - 40px), (max-width: 1728px) 46vw, 788px" width={1536} height={1024} alt={choose(language,'Версия баннера ВелоСОП 2026 года: пиксельные велосипеды, палатки и горы вокруг зелёного щита в вечерней сцене','VeloSOP 2026 banner version: pixel bicycles, tents and mountains around a green billboard in an evening scene')} loading="lazy" decoding="async"/><figcaption><span>02 / {choose(language,'БАННЕР','BANNER')}</span><span>2026</span></figcaption></figure>
</div>}

