'use client';
import {ZoomImage} from './zoom-image';
import {Reveal} from './site';
import {choose,useLanguage} from '../lib/i18n';

function LightingAsset({name,ru,en,kind='concept'}:{name:string;ru:string;en:string;kind?:'concept'|'mobile'|'guide'|'overview'}){const {language}=useLanguage();const dimensions=kind==='mobile'?[1080,1920]:kind==='guide'?[1447,2048]:kind==='overview'?[1171,1400]:[1600,1915];return <figure className="lighting-asset"><ZoomImage src={'/images/'+name+'.webp'} width={dimensions[0]} height={dimensions[1]} alt={choose(language,ru,en)} loading="lazy" decoding="async"/><figcaption>{choose(language,ru,en)}</figcaption></figure>}

export function LightingStory(){const {language}=useLanguage();return <div className="case-story wrap lighting-story">
  <Reveal className="story-text"><span className="eyebrow">01 / {choose(language,'О ПРОЕКТЕ','ABOUT')}</span><p>{choose(language,'LIGHTING — айдентика проекта об естественном освещении и инсоляции. Задача — собрать узнаваемый образ и перенести его в оформление сообщества VK: от знака и обложек до меню и инструкций по установке.','LIGHTING is an identity for a project about natural lighting and insolation. The brief brings a recognisable visual identity into a VK community, from the mark and covers to menu graphics and setup guides.')}</p></Reveal>
  <Reveal className="story-section"><span className="eyebrow">02 / {choose(language,'ЗНАК И ВИЗУАЛЬНЫЙ ЯЗЫК','MARK & VISUAL LANGUAGE')}</span><h2>{language==='ru'?<>СВЕТ.<br/>РИТМ. СИСТЕМА.</>:<>LIGHT.<br/>RHYTHM. SYSTEM.</>}</h2><div className="lighting-logo-panel"><ZoomImage src="/images/lighting-logo.webp" width={1241} height={1241} alt={choose(language,'Логотип проекта по освещению: два ряда жёлтых и серых радиальных элементов','Lighting project logo: two rings of yellow and grey radial elements')} loading="lazy" decoding="async"/></div><p>{choose(language,'Радиальный знак строится на чередовании жёлтых и серых элементов. Этот ритм продолжается в графике обложек; фотографии светлых интерьеров раскрывают тему естественного света.','The radial mark alternates yellow and grey elements. Its rhythm carries into the cover graphics, while photographs of bright interiors introduce the theme of natural light.')}</p></Reveal>
  <Reveal className="story-section"><span className="eyebrow">03 / {choose(language,'ОФОРМЛЕНИЕ СООБЩЕСТВА','COMMUNITY DESIGN')}</span><h2>{language==='ru'?<>ЕДИНЫЙ ОБРАЗ<br/>В VK.</>:<>ONE VISUAL IDENTITY<br/>IN VK.</>}</h2><div className="lighting-overview"><LightingAsset name="lighting-vk-overview" kind="overview" ru="Концепция оформления: обложка, аватар и меню VK" en="Community design concept: VK cover, avatar and menu"/></div></Reveal>
  <Reveal className="story-section"><span className="eyebrow">04 / {choose(language,'ПОИСК РЕШЕНИЯ · 6 КОНЦЕПЦИЙ','DESIGN EXPLORATION · 6 CONCEPTS')}</span><div className="lighting-concept-grid">{[1,2,3,4,5,6].map(i=><LightingAsset key={i} name={'lighting-concept-'+i} ru={'КОНЦЕПЦИЯ / 0'+i} en={'CONCEPT / 0'+i}/>)}</div></Reveal>
  <Reveal className="story-section"><span className="eyebrow">05 / {choose(language,'МОБИЛЬНЫЕ ОБЛОЖКИ','MOBILE COVERS')}</span><h2>{language==='ru'?<>ТОТ ЖЕ ХАРАКТЕР.<br/>ДРУГОЙ ФОРМАТ.</>:<>SAME CHARACTER.<br/>ANOTHER FORMAT.</>}</h2><div className="lighting-mobile-grid">{[1,2,3].map(i=><LightingAsset key={i} name={'lighting-mobile-'+i} kind="mobile" ru={'МОБИЛЬНАЯ ОБЛОЖКА / 0'+i} en={'MOBILE COVER / 0'+i}/>)}</div></Reveal>
  <Reveal className="story-section"><span className="eyebrow">06 / {choose(language,'ПЕРЕДАЧА И ВНЕДРЕНИЕ','HANDOFF & IMPLEMENTATION')}</span><h2>{language==='ru'?<>ДИЗАЙН,<br/>КОТОРЫМ ПОЛЬЗУЮТСЯ.</>:<>DESIGN<br/>READY TO USE.</>}</h2><div className="lighting-guide-grid"><LightingAsset name="lighting-guide-cover" kind="guide" ru="ИНСТРУКЦИЯ / ОБЛОЖКА VK" en="SETUP GUIDE / VK COVER"/><LightingAsset name="lighting-guide-menu" kind="guide" ru="ИНСТРУКЦИЯ / МЕНЮ VK" en="SETUP GUIDE / VK MENU"/></div><p>{choose(language,'К материалам подготовлены инструкции по загрузке обложки и настройке меню. Они помогают перенести дизайн в сообщество и поддерживать его оформление.','The materials include guides for uploading the cover and setting up the menu, helping bring the design into the community and maintain its appearance.')}</p></Reveal>
</div>}
