'use client';
import {ZoomImage} from './zoom-image';
import {Reveal} from './site';
import {choose,useLanguage} from '../lib/i18n';

export function LisyaNoraStory(){const {language}=useLanguage();return <div className="case-story wrap fox-story">
  <Reveal className="story-text"><span className="eyebrow">01 / {choose(language,'КОНТЕКСТ','CONTEXT')}</span><p>{choose(language,'«Лисья нора» — айдентика для бизнеса загородных коттеджей в аренду. В центре образа — дом и лиса: знак связывает название с местом, куда приезжают отдохнуть и почувствовать себя дома.','Lisya Nora is an identity for a countryside cottage rental business. The house and fox connect the name with a place to unwind and feel at home.')}</p></Reveal>
  <Reveal className="story-section"><span className="eyebrow">02 / {choose(language,'ЛОГОТИП И ХАРАКТЕР','LOGO & CHARACTER')}</span><h2>{language==='ru'?<>СВОЁ МЕСТО.<br/>ЗА ГОРОДОМ.</>:<>A PLACE OF YOUR OWN.<br/>OUT OF TOWN.</>}</h2><figure className="fox-logo-sheet"><ZoomImage src="/images/lisya-nora-logo.webp" alt={choose(language,'Логотип Лисья нора: крыша дома, оранжевый знак и лиса в надписи','Lisya Nora logo with a roof, orange mark and fox in the lettering')} loading="lazy" decoding="async"/></figure><p>{choose(language,'Оранжевый цвет, силуэт крыши и лиса внутри надписи задают характер бренда. Знак и название сохраняют узнаваемость на бумаге, ткани и в цифровых материалах.','Orange, the roof silhouette and the fox within the lettering define the brand’s character. The mark and name carry across paper, fabric and digital materials.')}</p></Reveal>
  <Reveal className="story-section"><span className="eyebrow">03 / {choose(language,'ВАРИАНТЫ ИСПОЛЬЗОВАНИЯ','APPLICATIONS')}</span><h2>{language==='ru'?<>НА БУМАГЕ.<br/>НА ТКАНИ.</>:<>ON PAPER.<br/>ON FABRIC.</>}</h2><div className="fox-applications">{[['lisya-nora-notebook','БЛОКНОТ','NOTEBOOK'],['lisya-nora-shirt','ФУТБОЛКА','T-SHIRT']].map(([name,ru,en])=><figure key={name}><ZoomImage src={'/images/'+name+'.webp'} srcSet={'/images/'+name+'-small.webp '+(name==='lisya-nora-shirt'?'734':'900')+'w, /images/'+name+'.webp '+(name==='lisya-nora-shirt'?'1467':'1800')+'w'} sizes="(max-width: 650px) calc(100vw - 40px), 46vw" alt={choose(language,'Мокап: '+ru.toLowerCase()+' с логотипом Лисья нора',en+' mockup with the Lisya Nora logo')} loading="lazy" decoding="async"/><figcaption>{choose(language,ru,en)}</figcaption></figure>)}</div></Reveal>
  <Reveal className="story-section fox-rental-section"><span className="eyebrow">04 / {choose(language,'АДАПТАЦИЯ ДЛЯ АРЕНДЫ КОТТЕДЖЕЙ · КОНЦЕПТЫ','COTTAGE RENTAL APPLICATIONS · CONCEPTS')}</span><h2>{language==='ru'?<>ОТ ВЫБОРА ДОМА<br/>ДО ПРИЕЗДА.</>:<>FROM CHOOSING A HOME<br/>TO ARRIVING.</>}</h2><div className="fox-rental-concepts">
    <figure><div className="fox-booking-concept"><span className="fox-concept-meta">{choose(language,'ЛИСЬЯ НОРА / КОТТЕДЖИ В АРЕНДУ','LISYA NORA / COTTAGE RENTALS')}</span><ZoomImage src="/images/lisya-nora-logo-small.webp" alt="" loading="lazy"/><h3>{choose(language,'Ваш дом за городом.','Your home in the countryside.')}</h3><p>{choose(language,'Выберите коттедж для своего отдыха.','Find a cottage for your getaway.')}</p><div className="fox-booking-fields"><span>{choose(language,'ДАТЫ ПОЕЗДКИ','TRAVEL DATES')}</span><span>{choose(language,'ГОСТИ','GUESTS')}</span></div><span className="fox-concept-action">{choose(language,'ВЫБРАТЬ ДОМ','CHOOSE A COTTAGE')}</span></div><figcaption>{choose(language,'КОНЦЕПТ / КАРТОЧКА ВЫБОРА КОТТЕДЖА','CONCEPT / COTTAGE SELECTION CARD')}</figcaption></figure>
    <figure><div className="fox-welcome-concept"><span className="fox-concept-meta">{choose(language,'ПАМЯТКА ГОСТЯ','GUEST GUIDE')}</span><ZoomImage src="/images/lisya-nora-logo-small.webp" alt="" loading="lazy"/><h3>{choose(language,'Вы на месте.','You have arrived.')}</h3><p>{choose(language,'Добро пожаловать в «Лисью нору».','Welcome to Lisya Nora.')}</p><div className="fox-guide-lines"><span>01 / {choose(language,'ЗАСЕЛЕНИЕ И КЛЮЧИ','CHECK-IN & KEYS')}</span><span>02 / {choose(language,'ВАШ КОТТЕДЖ','YOUR COTTAGE')}</span><span>03 / {choose(language,'СВЯЗЬ С ХОЗЯЕВАМИ','CONTACT YOUR HOST')}</span></div></div><figcaption>{choose(language,'КОНЦЕПТ / ПРИВЕТСТВЕННАЯ КАРТОЧКА','CONCEPT / WELCOME CARD')}</figcaption></figure>
  </div><p>{choose(language,'Предлагаемые применения айдентики для аренды: карточка помогает выбрать дом, памятка сопровождает гостя после бронирования. Оба концепта продолжают оранжево-чёрную палитру и характер логотипа.','Proposed rental applications: a card to help choose a cottage and a guide for guests after booking. These are identity adaptation concepts.')}</p></Reveal>
</div>}
