'use client';
import Link from './site-link';
import {LightingLaptop} from './lighting-laptop';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {imageDimensions} from '../lib/image-dimensions';
import {contact,Project} from '../lib/projects';
import {choose,localizeProject,useLanguage} from '../lib/i18n';

export function Header(){const path=usePathname();const {language,setLanguage}=useLanguage();const [compact,setCompact]=useState(false);const [aboutVisible,setAboutVisible]=useState(false);useEffect(()=>{const update=()=>{setCompact(window.scrollY>40);const about=document.getElementById('about');setAboutVisible(path==='/'&&!!about&&about.getBoundingClientRect().top<=120)};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[path]);const labels=language==='ru'?['РАБОТЫ','ОБО МНЕ','КОНТАКТЫ']:['WORK','ABOUT','CONTACT'];return <header className={'site-header wrap '+(compact?'compact':'')}><Link className="brand" href="/" aria-label={choose(language,'Андрей Слюта — главная','Andrey Sliuta — home')}><strong>{choose(language,'АНДРЕЙ СЛЮТА','ANDREY SLIUTA')}</strong><span>{choose(language,'ГРАФИЧЕСКИЙ ДИЗАЙНЕР','GRAPHIC DESIGNER')}</span></Link><div className="header-actions"><nav aria-label={choose(language,'Основная навигация','Primary navigation')}>{[['/work',labels[0]],['/#about',labels[1]],['/contact',labels[2]]].map(([href,label])=><Link key={href} className={href==='/#about'?(aboutVisible?'active':''):(path===href?'active':'')} href={href}>{label}</Link>)}</nav><div className="language-switch" role="group" aria-label={choose(language,'Язык сайта','Site language')}><button type="button" lang="ru" aria-pressed={language==='ru'} className={language==='ru'?'active':''} onClick={()=>setLanguage('ru')}>RU</button><span aria-hidden="true">/</span><button type="button" lang="en" aria-pressed={language==='en'} className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button></div></div></header>}
export function Footer(){const {language}=useLanguage();return <footer className="footer wrap"><div className="footer-top"><div>© 2026 {choose(language,'АНДРЕЙ СЛЮТА','ANDREY SLIUTA')}<br/><span>{choose(language,'ГРАФИЧЕСКИЙ ДИЗАЙНЕР','GRAPHIC DESIGNER')}</span></div><div className="footer-links"><a href={'mailto:'+contact.email}>{choose(language,'ПОЧТА','EMAIL')}</a><a href={contact.telegram} target="_blank" rel="noreferrer">TELEGRAM</a><a href={contact.resume} download="Andrey-Sliuta-Resume.doc">{choose(language,'РЕЗЮМЕ','RESUME')}</a></div><a className="back-to-top" href="#top"><span>↑</span> {choose(language,'НАВЕРХ','BACK TO TOP')}</a></div></footer>}
export function Reveal({children,className='',id}:{children:React.ReactNode;className?:string;id?:string}){const ref=useRef<HTMLDivElement>(null);const [seen,setSeen]=useState(false);useEffect(()=>{if(!ref.current)return;const io=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setSeen(true);io.disconnect()}},{rootMargin:'0px 0px -16% 0px',threshold:0});io.observe(ref.current);return()=>io.disconnect()},[]);return <div ref={ref} id={id} className={'reveal '+(seen?'seen ':'')+className}>{children}</div>}
export function PageMotion({children}:{children:React.ReactNode}){const path=usePathname();return <div key={path} className="page-enter">{children}</div>}
export function HeroScroll(){const {language}=useLanguage();const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const hero=ref.current?.closest<HTMLElement>('.hero');if(!hero)return;const letters=Array.from(hero.querySelectorAll<HTMLElement>('[data-scatter-letter]'));const groups=Array.from(hero.querySelectorAll<HTMLElement>('[data-scatter-group]'));const reduce=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const clamp=(value:number)=>Math.min(1,Math.max(0,value));const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const progress=clamp(window.scrollY/(window.innerHeight*.75));const spread=clamp((progress-.04)/.74);hero.style.setProperty('--hero-scroll',String(progress));hero.style.setProperty('--meta-opacity',String(1-spread));hero.classList.toggle('hero-metadata-gone',spread>.92);if(reduce.matches){for(const group of groups)group.style.opacity=String(1-spread);for(const letter of letters){letter.style.transform='';letter.style.opacity=''}return}for(const group of groups)group.style.opacity='';for(const letter of letters){const delay=Number(letter.dataset.delay||0);const local=clamp((spread-delay)/(1-delay));const travel=1-Math.pow(1-local,2.2);const x=Number(letter.dataset.vx||0)*travel;const y=Number(letter.dataset.vy||0)*travel;const rotation=Number(letter.dataset.rotation||0)*travel;letter.style.transform=`translate3d(${x.toFixed(1)}px,${y.toFixed(1)}px,0) rotate(${rotation.toFixed(1)}deg) scale(${(1-.18*travel).toFixed(3)})`;letter.style.opacity=String(1-local)}})};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[language]);return <div ref={ref} aria-hidden="true" className="hero-scroll-sensor"/>}
export function HeroScatterText({text,group=0}:{text:string;group?:number}){const glyphs=Array.from(text);return <span className="hero-scatter-text" data-scatter-group role="text" aria-label={text}>{glyphs.map((glyph,index)=>{const hash=(seed:number)=>{const value=Math.sin(seed*127.1+group*311.7)*43758.5453;return value-Math.floor(value)};const center=(index-(glyphs.length-1)/2)/Math.max(1,glyphs.length/2);const vx=center*(55+group*12)+(hash(index+1)-.5)*45;const vy=(hash(index+29)-.55)*130-Math.abs(center)*10;const rotation=(hash(index+67)-.5)*38;const delay=hash(index+113)*.13;return <span key={index} className="scatter-letter" aria-hidden="true" data-scatter-letter data-vx={vx.toFixed(1)} data-vy={vy.toFixed(1)} data-rotation={rotation.toFixed(1)} data-delay={delay.toFixed(3)}>{glyph===' '?'\u00a0':glyph}</span>})}</span>}
export function ContextCursor(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!matchMedia('(hover: hover) and (pointer: fine) and (prefers-reduced-motion: no-preference)').matches)return;let currentX=0,currentY=0,targetX=0,targetY=0,raf=0,active=false;const el=ref.current;if(!el)return;const tick=()=>{currentX+=(targetX-currentX)*.55;currentY+=(targetY-currentY)*.55;el.style.transform=`translate3d(${currentX}px,${currentY}px,0) translate(-50%,-50%)`;if(active)raf=requestAnimationFrame(tick)};const leave=()=>{active=false;cancelAnimationFrame(raf);el.classList.remove('is-visible')};const move=(e:PointerEvent)=>{const target=(e.target as Element)?.closest?.('[data-cursor]');const label=target?.getAttribute('data-cursor');if(!label){if(active)leave();return}targetX=e.clientX;targetY=e.clientY;el.textContent=label;if(!active){active=true;currentX=targetX;currentY=targetY;el.classList.add('is-visible');raf=requestAnimationFrame(tick)}};const out=(e:PointerEvent)=>{if(!e.relatedTarget)leave()};document.addEventListener('pointermove',move,{passive:true});document.addEventListener('pointerout',out,{passive:true});return()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerout',out);leave()}},[]);return <div ref={ref} className="context-cursor" aria-hidden="true"/>}
export function Visual({project,variant='',label}:{project:Project;variant?:string;label?:string}){const {language}=useLanguage();const p=localizeProject(project,language);if(p.slug==='lighting')return <div className={'visual project-image project-image-lighting laptop-visual '+variant}><LightingLaptop animate={variant!=='case-cover'}/></div>;const dimensions=p.cover?imageDimensions[p.cover.src]:[1824,1368];const smallDimensions=p.cover?imageDimensions[p.cover.small]:[960,720];if(p.cover&&(variant===''||variant==='case-cover'))return <div className={'visual project-image project-image-'+p.slug+' '+variant}><img src={p.cover.src} srcSet={p.cover.small+' '+smallDimensions[0]+'w, '+p.cover.src+' '+dimensions[0]+'w'} sizes={variant==='case-cover'?'(max-width: 650px) calc(100vw - 40px), (max-width: 1728px) calc(100vw - 128px), 1600px':'(max-width: 650px) calc(100vw - 40px), (max-width: 1728px) 66vw, 1060px'} width={dimensions[0]} height={dimensions[1]} alt={choose(language,p.cover.altRu,p.cover.altEn)} loading={variant==='case-cover'?'eager':'lazy'} decoding="async"/></div>;return <div className={'visual '+p.tone+' '+variant} role="img" aria-label={choose(language,'Временная композиция проекта ','Temporary composition for ')+p.title}><span className="visual-top">{p.number} / {p.type} <i>{choose(language,'ВРЕМЕННЫЙ ВИЗУАЛ','VISUAL PLACEHOLDER')}</i></span><div className="visual-title">{label||p.title}</div><span className="visual-bottom">{choose(language,'АНДРЕЙ СЛЮТА','ANDREY SLIUTA')} <span>{p.year}</span></span></div>}
export function ProjectRow({project,reverse=false}:{project:Project;reverse?:boolean}){const {language}=useLanguage();const p=localizeProject(project,language);return <Reveal className={'project-row '+(reverse?'reverse':'')}><div className="project-copy"><span className="eyebrow">{p.number} / {p.disciplines[0]}</span><h3>{p.title}</h3><div className="discipline">{p.disciplines.map(x=><span key={x}>{x}</span>)}</div><p>{p.description}</p><span className="year">{p.year}</span><Link className="text-link" href={'/work/'+p.slug}>{choose(language,'СМОТРЕТЬ КЕЙС','VIEW CASE')} <span>→</span></Link></div><Link href={'/work/'+p.slug} className="visual-link" data-cursor={choose(language,'СМОТРЕТЬ','VIEW')} aria-label={choose(language,'Открыть кейс ','View case ')+p.title}><Visual project={project}/></Link></Reveal>}
export function ContactCTA(){const {language}=useLanguage();return <section className="contact-cta wrap"><span className="eyebrow">{choose(language,'ЕСТЬ ПРОЕКТ? / 04','HAVE A PROJECT IN MIND? / 04')}</span><Reveal className="cta-mask"><Link href="/contact" className="contact-headline">{language==='ru'?<>ДАВАЙТЕ<br/>РАБОТАТЬ<br/><span className="accent-word">ВМЕСТЕ</span></>:<>LET’S<br/>WORK<br/><span className="accent-word">TOGETHER</span></>}<span className="corner-arrow">↗</span></Link></Reveal><p>{choose(language,'Есть проект, идея или хотите обсудить возможную работу — напишите.','Have a project or an idea? Get in touch and let’s talk.')}</p></section>}
export function CopyEmail(){const {language}=useLanguage();const [copied,setCopied]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);async function copy(){try{await navigator.clipboard.writeText(contact.email);setCopied(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),1500)}catch{window.location.href='mailto:'+contact.email}}return <button className={'text-link copy-button '+(copied?'copied':'')} data-cursor={choose(language,'КОПИРОВАТЬ','COPY')} type="button" onClick={copy} aria-live="polite">{copied?choose(language,'СКОПИРОВАНО ✓','COPIED ✓'):choose(language,'КОПИРОВАТЬ ПОЧТУ →','COPY EMAIL →')}</button>}

/** Dissolves content only as it exits beneath the sticky header. */
export function HeaderProximity(){const path=usePathname();const {language}=useLanguage();useEffect(()=>{const selector=[
  '.hero-top > span','.hero h1','.section-head > *','.project-copy > *','.project-row .visual-link',
  '.print-heading > *','.print-sheet > .visual','.print-sheet > .print-preview-image','.all-work','.about-preview > .eyebrow','.about-preview h2','.about-preview-foot > *',
  '.contact-cta > .eyebrow','.contact-cta .contact-headline','.contact-cta > p','.page-hero > *','.work-index .filters','.work-item > a','.catalog-card','.case-profile-card',
  '.about-opening-title > *','.about-opening-intro','.about-opening-facts','.about-portrait',
  '.about-process .about-section-label','.about-process .about-step','.about-print-placeholder','.about-print-meta',
  '.about-tools-panel .about-section-label','.about-tool-columns > div','.about-project-card',
  '.about-landscape > div','.about-statement > *','.about-contact > *',
  '.contact-page > .eyebrow','.contact-page > h1','.contact-page > p','.contact-list > div','.availability > span',
  '.case-hero > *','.case-visual','.story-text > *','.story-section > *','.case-stat > *','.result-metrics > span','.next-project > *',
  '.footer-top > *'
].join(',');let nodes:HTMLElement[]=[];const collect=()=>{const raw=Array.from(document.querySelectorAll<HTMLElement>(selector));nodes=raw.filter(node=>!raw.some(parent=>parent!==node&&parent.contains(node)))};collect();const header=document.querySelector<HTMLElement>('.site-header');if(!header)return;const reduce=matchMedia('(prefers-reduced-motion: reduce)');const mobile=matchMedia('(max-width: 650px)');let frame=0;const clamp=(v:number)=>Math.min(1,Math.max(0,v));const hash=(n:number)=>{const x=Math.sin(n*78.233)*43758.5453;return x-Math.floor(x)};const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const headerBottom=header.getBoundingClientRect().bottom;const zone=mobile.matches?48:64;for(let i=0;i<nodes.length;i++){const node=nodes[i];const rect=node.getBoundingClientRect();const p=clamp((headerBottom+zone-rect.bottom)/zone);const eased=p*p*(3-2*p);node.style.opacity=String(1-eased);node.style.pointerEvents=p>.96?'none':'';if(reduce.matches){node.style.translate='';node.style.rotate='';node.style.scale='';continue}const factor=mobile.matches?.55:1;const dx=(hash(i+3)>.5?1:-1)*(18+hash(i+17)*42)*eased*factor;const dy=(hash(i+53)-.5)*74*eased*factor;const angle=(hash(i+101)-.5)*10*eased;node.style.translate=`${dx.toFixed(1)}px ${dy.toFixed(1)}px`;node.style.rotate=`${angle.toFixed(1)}deg`;node.style.scale=String(1-.04*eased)}})};const observer=new MutationObserver(()=>{collect();update()});observer.observe(document.querySelector('main')||document.body,{childList:true,subtree:true});update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{observer.disconnect();cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);for(const node of nodes){node.style.opacity='';node.style.pointerEvents='';node.style.translate='';node.style.rotate='';node.style.scale=''}}},[path,language]);return null}
