export type Project={slug:string;number:string;title:string;year:string;disciplines:string[];description:string;tone:string;type:string;titleEn?:string;descriptionEn?:string;printItems?:import('../components/print-media').MediaKey[];cover?:{src:string;small:string;altRu:string;altEn:string}};
export const projects:Project[]=[
{slug:'velosop',number:'01',title:'VELOSOP',year:'2021—2026',disciplines:['VISUAL IDENTITY','ART DIRECTION','PRINT','DIGITAL','AI'],description:'Долгосрочная визуальная система велосипедного проекта: от айдентики и digital-коммуникации до мерча, печати и оформления мероприятия.',tone:'velo',type:'BRANDING',cover:{src:'/images/velosop-billboard.webp',small:'/images/velosop-billboard-small.webp',altRu:'Мокап наружного щита ВелоСОП: зелёный плакат с пиксельной графикой и велосипедным колесом',altEn:'VeloSOP outdoor billboard mockup: a green poster with pixel graphics and a bicycle wheel'}},
{slug:'lisya-nora',number:'02',title:'ЛИСЬЯ НОРА',year:'2024',disciplines:['BRAND IDENTITY','LOGO','PRINT','SOCIAL MEDIA'],description:'Айдентика бренда загородных коттеджей в аренду: логотип, печатные материалы, мерч и концепты коммуникации с гостями.',tone:'fox',type:'BRANDING',cover:{src:'/images/lisya-nora-kraft.webp',small:'/images/lisya-nora-kraft-small.webp',altRu:'Логотип Лисья нора на крафтовой бумаге',altEn:'Lisya Nora logo on kraft paper'}},
{slug:'lighting',number:'03',title:'LIGHTING',year:'2025',disciplines:['BRAND IDENTITY','LOGO','DIGITAL','SOCIAL MEDIA'],description:'Айдентика проекта в сфере естественного освещения и инсоляции: логотип, концепции оформления VK, мобильные обложки и инструкции по внедрению.',tone:'lighting',type:'DIGITAL',cover:{src:'/images/lighting-cover.webp',small:'/images/lighting-cover-small.webp',altRu:'Жёлтый баннер проекта естественного освещения с радиальным логотипом',altEn:'Yellow natural lighting project banner with the radial logo'}},
{slug:'print-production',number:'04',title:'PRINT PRODUCTION',year:'2023—2026',disciplines:['GRAPHIC DESIGN','PREPRESS','PRINT','PRODUCTION'],description:'Подборка проектов, прошедших путь от цифрового макета до физического носителя.',tone:'print',type:'PRINT',cover:{src:'/images/print-kontrofors-calendar.webp',small:'/images/print-kontrofors-calendar-small.webp',altRu:'Мокап квартального календаря Контрфорс',altEn:'Kontrofors quarterly calendar mockup'}},
{"slug": "wedding", "number": "05", "title": "СВАДЕБНОЕ ОФОРМЛЕНИЕ", "titleEn": "WEDDING DESIGN", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Оформление свадьбы: приглашение, меню и именные карточки в единой визуальной системе.", "descriptionEn": "Wedding design: invitations, menus and place cards in a shared visual system.", "tone": "print", "type": "PRINT", "printItems": ["weddingMenu", "weddingGuest", "weddingInside", "weddingOutside"], "cover": {"src": "/images/wedding-menu.webp", "small": "/images/wedding-menu-small.webp", "altRu": "Свадебное меню на льняной скатерти", "altEn": "Wedding menu on a linen tablecloth"}},
{"slug": "kontrofors", "number": "06", "title": "КОНТРФОРС", "titleEn": "KONTROFORS", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Календарь и деловые карточки Контрфорса: геометрическая графика на печатных носителях.", "descriptionEn": "A Kontrofors calendar and business cards: geometric graphics across printed materials.", "tone": "print", "type": "PRINT", "printItems": ["calendar", "cards"], "cover": {"src": "/images/print-kontrofors-calendar.webp", "small": "/images/print-kontrofors-calendar-small.webp", "altRu": "КОНТРФОРС", "altEn": "KONTROFORS"}},
{"slug": "barber-academy", "number": "07", "title": "АКАДЕМИЯ БАРБЕРОВ", "titleEn": "BARBER ACADEMY", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Рабочие тетради и оформление пространства для сети академий барберов.", "descriptionEn": "Workbooks and signage for a network of barber academies.", "tone": "print", "type": "PRINT", "printItems": ["workbook", "door"], "cover": {"src": "/images/print-barber-workbook.webp", "small": "/images/print-barber-workbook-small.webp", "altRu": "АКАДЕМИЯ БАРБЕРОВ", "altEn": "BARBER ACADEMY"}},
{"slug": "restaurant-menus", "number": "08", "title": "РЕСТОРАННЫЕ МЕНЮ", "titleEn": "RESTAURANT MENUS", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Печатные материалы «Старик-Хинкалыч» и создание и редактирование меню «Мама Токио».", "descriptionEn": "Printed materials for Staryk Khinkalych and menu design and editing for Mama Tokio.", "tone": "print", "type": "PRINT", "printItems": ["staryk", "tokio"], "cover": {"src": "/images/print-staryk-menu.webp", "small": "/images/print-staryk-menu-small.webp", "altRu": "РЕСТОРАННЫЕ МЕНЮ", "altEn": "RESTAURANT MENUS"}},
{"slug": "posters", "number": "09", "title": "АФИШИ И ПЛАКАТЫ", "titleEn": "POSTERS", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Плакаты OKKO и «Балет на льду»: фотографии материалов в производстве и готовых тиражей.", "descriptionEn": "OKKO and Ice Ballet posters: photographs of materials in production and finished print runs.", "tone": "print", "type": "PRINT", "printItems": ["okko", "ballet"], "cover": {"src": "/images/print-ice-ballet-posters.webp", "small": "/images/print-ice-ballet-posters-small.webp", "altRu": "АФИШИ И ПЛАКАТЫ", "altEn": "POSTERS"}},
{"slug": "nevskaya-usadba", "number": "10", "title": "НЕВСКАЯ УСАДЬБА", "titleEn": "NEVSKAYA USADBA", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Буклеты для «Невской усадьбы»: фотографии готовых печатных материалов.", "descriptionEn": "Brochures for Nevskaya Usadba: photographs of finished printed materials.", "tone": "print", "type": "PRINT", "printItems": ["brochures"], "cover": {"src": "/images/print-nevskaya-brochures.webp", "small": "/images/print-nevskaya-brochures-small.webp", "altRu": "НЕВСКАЯ УСАДЬБА", "altEn": "NEVSKAYA USADBA"}},
{"slug": "health-notebooks", "number": "11", "title": "FIZ PROPAGANDA", "titleEn": "FIZ PROPAGANDA", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Блокноты для компании в сфере заботы о здоровье.", "descriptionEn": "Notebooks for a company in the health care sector.", "tone": "print", "type": "PRINT", "printItems": ["notebooks"], "cover": {"src": "/images/print-health-notebooks.webp", "small": "/images/print-health-notebooks-small.webp", "altRu": "FIZ PROPAGANDA", "altEn": "FIZ PROPAGANDA"}},
{"slug": "event-invitation", "number": "12", "title": "ПРИГЛАСИТЕЛЬНЫЙ", "titleEn": "EVENT INVITATION", "year": "—", "disciplines": ["GRAPHIC DESIGN", "DIGITAL"], "description": "Приглашение на Pre-Party: исходный макет и три варианта для рассылки в мессенджерах.", "descriptionEn": "A Pre-Party invitation: original artwork and three variations for messenger distribution.", "tone": "print", "type": "DIGITAL", "printItems": ["invitation"], "cover": {"src": "/images/print-invitation.webp", "small": "/images/print-invitation-small.webp", "altRu": "ПРИГЛАСИТЕЛЬНЫЙ", "altEn": "EVENT INVITATION"}},
{"slug": "business-card", "number": "13", "title": "ВИЗИТКА", "titleEn": "BUSINESS CARD", "year": "—", "disciplines": ["GRAPHIC DESIGN", "PRINT"], "description": "Визитка Контрфорса: знак и зелёная геометрическая графика на двух сторонах карточки.", "descriptionEn": "Kontrofors business card: a mark and green geometric graphics on both sides.", "tone": "print", "type": "PRINT", "printItems": ["business"], "cover": {"src": "/images/print-business-card.webp", "small": "/images/print-business-card-small.webp", "altRu": "ВИЗИТКА", "altEn": "BUSINESS CARD"}}];
export const contact={email:'I1nc2dsgn@gmail.com',telegram:'https://t.me/l1nc9ln',telegramLabel:'@l1nc9ln',resume:'/files/andrey-sliuta-resume.doc'};
